"""empty message

Revision ID: 084517c9aa51
Revises: 
Create Date: 2025-10-20 14:57:06.706333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084517c9aa51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('servicio', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('barbero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barbero_id'], ['barbero.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita')
    op.drop_table('cliente')
    op.drop_table('barbero')
    # ### end Alembic commands ###
