"""empty message

Revision ID: b35013736546
Revises: b4e4eba08678
Create Date: 2025-10-22 16:26:10.382170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35013736546'
down_revision = 'b4e4eba08678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dia_restringido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dia_restringido', schema=None) as batch_op:
        batch_op.drop_column('hora')

    # ### end Alembic commands ###
