"""empty message

Revision ID: ee940f15f044
Revises: b35013736546
Create Date: 2025-10-22 17:40:22.111315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee940f15f044'
down_revision = 'b35013736546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dia_restringido', schema=None) as batch_op:
        batch_op.drop_index('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dia_restringido', schema=None) as batch_op:
        batch_op.create_index('fecha', ['fecha'], unique=False)

    # ### end Alembic commands ###
