"""empty message

Revision ID: f1374e079b63
Revises: b80815b40942
Create Date: 2025-10-21 14:20:41.032767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1374e079b63'
down_revision = 'b80815b40942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('hora',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Time(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
